##############################################
## Script generated by Konstantinos Kougioumoutzis#############################################
## for the study entitled: Migrating the  extinction risk of globally threatened and endemic ##
## mountainous Orthoptera species: Parnassiana parnassica and Oropodisma parnassica ###########
###############################################################################################

# SDM Analyses

# 1_Distribution range and thinning


##============================================================================##
## Load required libraries
##============================================================================##
library(sf)
library(tidyverse)
library(CoordinateCleaner)
library(ConR)
library(mapview)
library(spThin)
##============================================================================##

##============================================================================##
## Set working directory
##============================================================================##
setwd('your/directory/here')
##============================================================================##

##============================================================================##
## Prepare the data
##============================================================================##
data <- readxl::read_excel('your_data.xlsx', sheet = 2) %>% 
  janitor::clean_names() %>% 
  dplyr::select(species, lat, lon) %>% 
  distinct(species, lat, lon)

coords_arranged <- data %>% 
  rename(Species = species) %>% 
  distinct(Species) %>%
  mutate(Taxon = paste0('A', 1:2)) %>% 
  as_tibble()
##============================================================================##

##============================================================================##
## Prepare data for alpha-hull estimation
##============================================================================##
coords_alpha <- data %>%
  dplyr::select(lat, lon, species) %>%
  arrange(species) %>% 
  as.data.frame()

coords_alpha <- coords_alpha[order(match(coords_alpha[,3], coords_arranged[,1])),]
##============================================================================##

##============================================================================##
## Load official distribution range data
##============================================================================##
range_data_1 <- read_sf("path_to_your_shapefile_1.shp")
range_data_2 <- read_sf("path_to_your_shapefile_2.shp")
##============================================================================##

##============================================================================##
## Estimate the alpha-hull
##============================================================================##
country_map <- geodata::gadm(country = 'Country_Code', level = 0, path = getwd()) %>% 
  st_as_sf() 

alpha_hull <- EOO.computing(coords_alpha,
                            exclude.area = TRUE,
                            country_map = country_map,
                            export_shp = TRUE,
                            write_shp = TRUE,
                            parallel = TRUE,
                            NbeCores = 2,
                            show_progress = TRUE,
                            method.less.than3 = 'arbitrary',
                            method.range = 'alpha.hull')

ahull_eoo <- alpha_hull$results %>%
  rename(Taxon = tax, EOO = eoo) %>% 
  select(Taxon, EOO) %>%
  as_tibble()

ahull <- alpha_hull$spatial %>% 
  rename(Taxon = tax)

saveRDS(ahull_eoo, 'RDS/EOO_dataframe.rds')
saveRDS(ahull, 'RDS/Alpha_hulls.rds')
##============================================================================##

##============================================================================##
## Plot the final data
##============================================================================##
mapview(ahull[1,], 
        map.types = 'Esri.WorldImagery',
        col.regions = 'lightblue') + 
  mapview(data %>% 
            filter(str_detect(species, 'Species1')) %>% 
            st_as_sf(coords = c('lon', 'lat'), crs = 4326),
          z_col = 'species', 
          map.types = 'Esri.WorldImagery',
          col.regions = 'green4',
          legend = TRUE)

mapview(ahull[2,], 
        map.types = 'Esri.WorldImagery',
        col.regions = 'lightblue') + 
  mapview(data %>% 
            filter(!str_detect(species, 'Species1')) %>% 
            st_as_sf(coords = c('lon', 'lat'), crs = 4326),
          z_col = 'species', 
          map.types = 'Esri.WorldImagery',
          col.regions = 'green4',
          legend = TRUE)
##============================================================================##

##============================================================================##
## Thin the data
##============================================================================##
cleaned_data <- data %>% 
  clean_coordinates(lon = 'lon', lat = 'lat', species = 'species',
                    tests = c("capitals", "centroids", "equal", 
                              "gbif", "institutions", "seas", "zeros")) %>% 
  filter(.summary == TRUE) %>% 
  select(species, lon, lat)

thinned <- list()
species_names <- unique(cleaned_data$species)

for(i in seq_along(species_names)){
  thinned[[i]] <- spThin::thin(loc.data = subset(cleaned_data, species == species_names[i]), 
                               lat.col = "lat", 
                               long.col = "lon", 
                               spec.col = "species", 
                               thin.par = 0.0925, 
                               reps = 10, 
                               verbose = TRUE, 
                               out.dir = "Thinned", 
                               locs.thinned.list.return = TRUE, 
                               write.files = TRUE, 
                               out.base = species_names[i],
                               max.files = 1)[[1]] %>% 
    mutate(Taxon = species_names[i])
}

thinned_data <- do.call(rbind, thinned)

saveRDS(thinned_data, 'RDS/Thinned_coords_100m_resolution.rds')
##============================================================================##

##============================================================================##
## Check the Nearest Neighbour Index (NNI)
##============================================================================##
eliminated_data <- thinned_data %>%
  distinct(Taxon, lon, lat) %>%
  st_as_sf(coords = c('lon', 'lat'), crs = 4326)

nni_species_1 <- nni(eliminated_data %>% filter(str_detect(Taxon, 'Species1')), win = "extent")
nni_species_2 <- nni(eliminated_data %>% filter(!str_detect(Taxon, 'Species1')), win = "extent")

## Check the final NNI
nni_species_1$observed.mean.distance * 111
nni_species_2$observed.mean.distance * 111
##============================================================================##
