##############################################
## Script generated by Konstantinos Kougioumoutzis#############################################
## for the study entitled: Migrating the  extinction risk of globally threatened and endemic ##
## mountainous Orthoptera species: Parnassiana parnassica and Oropodisma parnassica ###########
###############################################################################################


# SDM Analyses

# 2_Create and download NDVI data with rgee


##============================================================================##
## Load required libraries
##============================================================================##
library(rgee)
library(sf)
library(terra)
library(tidyverse)
##============================================================================##

##============================================================================##
## Set working directory
##============================================================================##
setwd('your/directory/here')
##============================================================================##

##============================================================================##
## Initialize Google Earth Engine (GEE)
##============================================================================##
ee_Initialize(user = 'your_email_here@gmail.com')
##============================================================================##

##============================================================================##
## Load the region of interest shapefile
##============================================================================##
region_of_interest <- readRDS('RDS/Alpha_hulls.rds')
area_1 <- region_of_interest[1,]
area_2 <- region_of_interest[2,]
##============================================================================##

##============================================================================##
## Set the region of interest
##============================================================================##
roi <- area_1
##============================================================================##

##============================================================================##
## Convert region to GEE object
##============================================================================##
ee_geometry <- rgee::sf_as_ee(roi)
##============================================================================##

##============================================================================##
## Filter the Sentinel-2 dataset
##============================================================================##
s2_collection <- ee$ImageCollection("COPERNICUS/S2")$
  filterDate('2020-07-01', '2020-08-31')$
  filterBounds(ee_geometry)
##============================================================================##

##============================================================================##
## Define and apply a cloud mask function
##============================================================================##
maskClouds <- function(image) {
  qa <- image$select("QA60")
  cloudBitMask <- bitwShiftL(1, 10)
  cirrusBitMask <- bitwShiftL(1, 11)
  mask <- qa$bitwiseAnd(cloudBitMask)$eq(0)$And(qa$bitwiseAnd(cirrusBitMask)$eq(0))
  return(image$updateMask(mask))
}

s2_masked <- s2_collection$map(maskClouds)
##============================================================================##

##============================================================================##
## Calculate NDVI
##============================================================================##
calculate_ndvi <- function(image) {
  ndvi <- image$normalizedDifference(c("B8", "B4"))$rename("NDVI")
  ndvi_reprojected <- ndvi$reproject(crs = image$select("B4")$projection(), scale = 100)
  return(ndvi_reprojected)
}

ndvi_collection <- s2_masked$map(calculate_ndvi)
##============================================================================##

##============================================================================##
## Export the NDVI data to Google Drive
##============================================================================##
task <- ee$batch$Export$image$toDrive(
  image = ndvi_collection$mean(),
  description = "ndvi_export",
  folder = "NDVI_Data",
  fileNamePrefix = "ndvi_july_august_2020",
  region = ee_geometry$geometry()$bounds(),
  scale = 100,
  maxPixels = 1e13
)
task$start()
##============================================================================##

##============================================================================##
## Load and visualize the NDVI data
##============================================================================##
ndvi_test <- rast("NDVI/your_folder/ndvi_july_august_2020.tif")
plot(ndvi_test %>% crop(., area_1, snap = 'in', mask = TRUE))
##============================================================================##
