##############################################
## Script generated by Konstantinos Kougioumoutzis#############################################
## for the study entitled: Migrating the  extinction risk of globally threatened and endemic ##
## mountainous Orthoptera species: Parnassiana parnassica and Oropodisma parnassica ###########
###############################################################################################


# SDM Analyses

# 3_EuClim IVs based on the official IUCN distributional range


##============================================================================##
## Load required libraries
##============================================================================##
library(raster)
library(envirem)
library(sf)
library(dplyr)
library(tidyr)
library(spatialEco)
##============================================================================##

##============================================================================##
## Set working directory
##============================================================================##
setwd('your/directory/here')
##============================================================================##

##============================================================================##
## Load the official IUCN distribution range
##============================================================================##
distribution_range_1 <- read_sf("path_to_your_shapefile_1.shp")
distribution_range_2 <- read_sf("path_to_your_shapefile_2.shp")
##============================================================================##

##============================================================================##
## Load and crop the high-resolution DEM
##============================================================================##
dem_1 <- readRDS("path_to_your_dem_file.rds") %>%
  terra::rast() %>%
  terra::crop(., distribution_range_1, snap = 'in', mask = TRUE)

dem_2 <- readRDS("path_to_your_dem_file.rds") %>%
  terra::rast() %>%
  terra::crop(., distribution_range_2, snap = 'in', mask = TRUE)
##============================================================================##

##============================================================================##
## Convert DEM to a dataframe with XY coordinates
##============================================================================##
dem_df_1 <- dem_1 %>%
  as.data.frame(xy = TRUE) %>%
  drop_na() %>%
  rename(Elevation = layer)

dem_df_2 <- dem_2 %>%
  as.data.frame(xy = TRUE) %>%
  drop_na() %>%
  rename(Elevation = layer)
##============================================================================##

##============================================================================##
## Save as CSV for Climate-EU
##============================================================================##
dem_df_1 %>%
  mutate(id1 = 1:NROW(.), id2 = 1:NROW(.)) %>%
  select(id1, id2, y, everything()) %>%
  write.csv(., 'path_to_your_output_1.csv', row.names = FALSE)

dem_df_2 %>%
  mutate(id1 = 1:NROW(.), id2 = 1:NROW(.)) %>%
  select(id1, id2, y, everything()) %>%
  write.csv(., 'path_to_your_output_2.csv', row.names = FALSE)
##============================================================================##

##============================================================================##
## Load Climate-EU output and join with DEM data
##============================================================================##
climate_eu_output <- read.csv('path_to_your_climate_eu_output.csv') %>%
  select(Longitude, Latitude, everything())

joined_data <- full_join(climate_eu_output, dem_df_1) %>%
  select(-c(Longitude, Latitude, id1, id2)) %>%
  select(x, y, everything()) %>%
  drop_na() %>%
  filter(Tave01 > -9999) %>%
  rasterFromXYZ() %>%
  stack()

saveRDS(joined_data, 'path_to_your_output_rds.rds')
##============================================================================##

##============================================================================##
## Create WorldClim variables
##============================================================================##
worldclim_vars <- dismo::biovars(joined_data[[38:49]], 
                                 joined_data[[26:37]], 
                                 joined_data[[14:25]])

crs(worldclim_vars) <- crs(dem_1)
saveRDS(worldclim_vars, 'path_to_your_worldclim_output.rds')
##============================================================================##

##============================================================================##
## Calculate solar radiation rasters for 2020
##============================================================================##
wc <- rast(worldclim_vars)
crs(wc) <- crs(dem_1)

ETsolradRasters(rasterTemplate = wc[[19]],
                year = 70,
                outputDir = 'path_to_your_solar_radiation_output',
                overwrite = TRUE)

solar_rasters <- stack(list.files('path_to_your_solar_radiation_output',
                                  pattern = 'solrad',
                                  full.names = TRUE)) %>%
  rast()
##============================================================================##

##============================================================================##
## Create envirem variables
##============================================================================##
envirem_vars <- generateEnvirem(c(wc, joined_data %>% rast()),
                                solar_rasters,
                                var = 'all')

saveRDS(envirem_vars, 'path_to_your_envirem_output.rds')
##============================================================================##

##============================================================================##
## Combine climate and envirem variables
##============================================================================##
combined_climate_vars <- c(wc, envirem_vars)
##============================================================================##

##============================================================================##
## Create topographical variables
##============================================================================##
slope <- terrain(dem_1, 'slope')
aspect <- terrain(dem_1, 'aspect')
hli <- hli(dem_1)
tpi <- tpi(dem_1)
tri <- tri(dem_1)

topo_vars <- c(slope, aspect, hli, tpi, tri, dem_1)
names(topo_vars) <- c('slope', 'aspect', 'hli', 'tpi', 'tri', 'altitude')

saveRDS(topo_vars, 'path_to_your_topo_output.rds')
##============================================================================##

##============================================================================##
## Load and process NDVI data
##============================================================================##
ndvi_data <- rast("path_to_your_ndvi_file.tif") %>%
  terra::crop(., distribution_range_1, snap = 'in', mask = TRUE)

ndvi_resampled <- resample(ndvi_data, combined_climate_vars, method = 'bilinear')
##============================================================================##

##============================================================================##
## Combine all variables
##============================================================================##
all_vars <- c(combined_climate_vars, topo_vars, ndvi_resampled)
##============================================================================##

##============================================================================##
## Check for correlation and filter uncorrelated variables
##============================================================================##
uncorrelated_vars <- usdm::vifcor(all_vars %>% as.data.frame(), th = 0.7)@results$Variables

uncorrelated_vars2 <- collinear::collinear(all_vars %>% 
                                             as.data.frame(),
                                           cor_method = 'spearman',
                                           max_cor = 0.7,
                                           max_vif = 5)

saveRDS(uncorrelated_vars, 'path_to_your_uncorrelated_vars_output.rds')
saveRDS(uncorrelated_vars2, 'path_to_your_uncorrelated_vars2_output.rds')
##============================================================================##

##============================================================================##
## Subset variables based on uncorrelated sets
##============================================================================##
all_vars_subset <- all_vars %>%
  subset(., uncorrelated_vars)

saveRDS(all_vars_subset, 'path_to_your_subset_output.rds')

all_vars_subset2 <- all_vars %>%
  subset(., uncorrelated_vars2)

saveRDS(all_vars_subset2, 'path_to_your_subset2_output.rds')
##============================================================================##
